name: Streamlit Keep Alive

on:
  schedule:
    # Executa a cada 12 horas todos os dias.
    - cron: '0 */12 * * *'
  # Botão de teste manual.
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Reativar aplicação xml-for-danfe
        run: |
          curl -sL -o /dev/null -w "%{http_code}\n" https://xml-for-danfe.streamlit.app/